steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/eigenvalue-dev/colpali-backend', 'colpali-backend']
    timeout: '1800s'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/eigenvalue-dev/colpali-backend']

images:
  - 'gcr.io/eigenvalue-dev/colpali-backend'

options:
  machineType: 'N1_HIGHCPU_8'
  diskSizeGb: '100'
  logging: CLOUD_LOGGING_ONLY 